version: '3.8'

services:
  # ----------------------------------------------------------------
  # APLICACIÓN (PROD/CANARY)
  # ----------------------------------------------------------------

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "8085:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro 
    networks:
      - payflow-network

  app-prod:
    build: 
      context: ./app
    container_name: app-prod
    environment:
      - PORT=3000
      - APP_VERSION=stable
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318/v1/traces
    ports:
      - "3001:3000"
    networks:
      - payflow-network
    labels:
      org.label-schema.version: "stable"

  app-canary:
    build: 
      context: ./app
    container_name: app-canary
    environment:
      - PORT=3000
      - APP_VERSION=canary_test
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318/v1/traces
    ports:
      - "3002:3000"
    networks:
      - payflow-network
    labels:
      org.label-schema.version: "canary_test"

  # ----------------------------------------------------------------
  # SISTEMA DE MONITOREO (Observabilidad Completa)
  # ----------------------------------------------------------------

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - payflow-network

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      # Configuración
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
      # Volumen persistente recomendado
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - payflow-network

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - payflow-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./monitoring/tempo.yaml:/etc/tempo.yaml
    ports:
      - "4318:4318"
    networks:
      - payflow-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - payflow-network

networks:
  payflow-network:
    driver: bridge

volumes:
  loki-data:
    driver: local
