global:
  scrape_interval: 10s 

scrape_configs:
  - job_name: 'validator-app'
    # Raspa los contenedores de la aplicación (producción, canary)
    static_configs:
      - targets: 
          # Nombres de servicio en docker-compose
          - 'app-prod:3000' 
          - 'app-canary:3000'
    metrics_path: /metrics